### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by petk** [php-earth/stats#19]
Translation messages for the generated stats report are located in [app/translations](https://github.com/wwphp-fb/stats/tree/master/app/translations) using the Symfony Translation Component and in the [YAML format](http://yaml.org/). Variables in messages are in the format `%variable%`.

Pluralization for languages with multiple pluralization formats:
- English and languages with 1 plural format:
  
  `"1 comment|%count% comments"`
- Russian and languages with 2 plural formats - first for 1 item, second for 2 items and third for 3 or more items:
  
  `"1 комментарий|%count% комментария|%count% комментариев"`
- Slovenian and languages with 3 plural formats - first for 1 item, second for 2 items, third for 3 and 4 items and fourth for 5 or more items:
  
  `"1 komentar|%count% komentarja|%count% komentarji|%count% komentarjev"`
- [ ] Add your translation. Every help is welcome.
- [x] Afrikaans (af_ZA) @rossiza
- [x] Arabic (ar) @stodar
- [x] Belarusian (bl) @p0v1n0m
- [x] Bengali (bn) @icic13 
- [x] Catalan (ca) @wolframtheta
- [x] Croatian (hr) @mjurinic 
- [x] Czech (cs) @StrnadRichard 
- [x] Dutch (nl) @veloxy 
- [x] French (fr) @I-am-me, @Tititesouris 
- [x] German (de) @michaspiss
- [x] Hindi (hi) @paraschadha2052 
- [x] Hungarian (hu) @Hunrik
- [x] Indonesian (id) @justthegame 
- [x] Malay (my) @codegateau 
- [x] Norwegian (nb) @RainoBoy97
- [x] Polish (pl) @Aylard
- [x] Portuguese (pt_BR) @IgorAntun 
- [x] Russian (ru) @p0v1n0m
- [x] Slovak (sk) @palosopko
- [x] Spanish (es) @jslirola 
- [x] Swedish (sv) @kajes
- [x] Tagalog (tl) @norvinyecla
- [x] Turkish (tr) @bureken
- [x] Ukrainian (uk) @andyps

Big thanks to all translators!

**Comment by IgorAntun** [comment]
I'll take care of Portuguese (pt_BR) :)

**Comment by peterkokot** [comment]
Great. Much appreciated. Thank you @IgorAntun

**Comment by wolframtheta** [comment]
I can translate it to Catalan if you want :)

**Comment by peterkokot** [comment]
Definitely, @wolframtheta 
Help would be much appreciated :+1:

**Comment by Hunrik** [comment]
I translated it to Hungarian :)
#38

**Comment by peterkokot** [comment]
Thanks @Hunrik for Hungarian translation. It has been merged :+1:

**Comment by kajes** [comment]
Added pull request for Swedish translation.

**Comment by peterkokot** [comment]
Great. Thanks @kajes

**Comment by icic13** [comment]
I can translate to Bengali.

**Comment by peterkokot** [comment]
@icic13 Bengali language would be great... Any help is welcome. :+1:  Thank you.

**Comment by codegateau** [comment]
Done Malay translation

**Comment by peterkokot** [comment]
@codegateau thank you, Malay translation merged as well.

**Comment by petk** [comment]
Closing via f74548600145a6a30dd6ec43eb926c9fa4b5c9d2

Thank you again everyone who has participated in translating this application. :+1:
