### ISSUE TITLE
Crey/conjurer commit-ref. 

### ISSUE THREAD

**Issue by mike-bailey** [php-earth/stats#48]
"The package "crey/conjurer" is pointing to a commit-ref, this is bad practice and can cause unforeseen issues." is keeping us from Platinum medal.

**Comment by nhlm** [comment]
`crey/conjurer` will be abandoned soon in favor of `subcosm/conjurer`. I didn't inspect the source deeply, do this package really use conjurer at all (also an unstable version) ?

**Comment by mike-bailey** [comment]
for being a mod I really don't know much about industry level (OOP and dependencies mainly) in PHP specifically but it's referenced at https://github.com/php-earth/stats/blob/037923552c0afbade50eeaab6d6b63197b475d86/app/bootstrap.php and initialized for $container

**Comment by petk** [comment]
Should be fixed now. For the time being I've added the Symfony Dependency Injection component instead.
